{
 "title": "Cube via SQL API",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Orders: Amount, by First Name",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT raw_customers_first_name,\n  MEASURE(orders.raw_payments_total_amount)\nFROM orders\nGROUP BY 1\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Order Amount by Payment Method",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT raw_payments_payment_method,\n  MEASURE(orders.raw_payments_total_amount)\nFROM orders\nGROUP BY 1\nORDER BY 2 DESC"
    }
   ]
  },
  {
   "title": "Orders: Amount and Count, by First Name",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "test",
     "rawSql": "SELECT raw_customers_first_name,\n  raw_customers_last_name,\n  MEASURE(orders.raw_payments_total_amount),\n  MEASURE(orders.raw_payments_count)\nFROM orders\nGROUP BY 1, 2\nORDER BY 3 DESC"
    }
   ]
  },
  {
   "title": "Supports SQL Expressions! Top 5, name fields merged",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expression": "SELECT\n  CONCAT(`raw_customers_first_name`, ' ', `raw_customers_last_name`) AS full_name,\n  `measure(orders.raw_payments_total_amount)`,\n  `measure(orders.raw_payments_count)`\nFROM A LIMIT 5",
     "type": "sql"
    }
   ]
  }
 ]
}