{
 "title": "GrafanaCon2026 RevOps use-case",
 "time": { "from": "now/fy", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "filter_account_owner_l1_territory",
    "label": "L1 Territory",
    "query": "select distinct(account_owner_l1_territory)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\norder by 1"
   },
   {
    "name": "filter_account_owner_l3_territory",
    "label": "L3 Territory",
    "query": "select distinct(account_owner_l3_territory)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_l1_territory in (${filter_account_owner_l1_territory:singlequote})\n\norder by 1"
   },
   {
    "name": "filter_account_owner_l4_territory",
    "label": "L4 Territory",
    "query": "select distinct(account_owner_l4_territory)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_l1_territory in (${filter_account_owner_l1_territory:singlequote})\n  and account_owner_l3_territory in (${filter_account_owner_l3_territory:singlequote})\n\norder by 1"
   },
   {
    "name": "filter_account_owner_l6_territory",
    "label": "L6 Territory",
    "query": "select distinct(account_owner_l6_territory)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_l1_territory in (${filter_account_owner_l1_territory:singlequote})\n  and account_owner_l3_territory in (${filter_account_owner_l3_territory:singlequote})\n  and account_owner_l4_territory in (${filter_account_owner_l4_territory:singlequote})\n\norder by 1"
   },
   {
    "name": "filter_account_owner_segment",
    "label": "Segment",
    "query": "select distinct(account_owner_segment)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_l1_territory in (${filter_account_owner_l1_territory:singlequote})\n  and account_owner_l3_territory in (${filter_account_owner_l3_territory:singlequote})\n  and account_owner_l4_territory in (${filter_account_owner_l4_territory:singlequote})\n  and account_owner_l6_territory in (${filter_account_owner_l6_territory:singlequote})\n\norder by 1"
   },
   {
    "name": "filter_account_owner_seller_type",
    "label": "Seller Type",
    "query": "select distinct(account_owner_seller_type)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_l1_territory in (${filter_account_owner_l1_territory:singlequote})\n  and account_owner_l3_territory in (${filter_account_owner_l3_territory:singlequote})\n  and account_owner_l4_territory in (${filter_account_owner_l4_territory:singlequote})\n  and account_owner_l6_territory in (${filter_account_owner_l6_territory:singlequote})\n  and account_owner_segment      in (${filter_account_owner_segment:singlequote})\n\norder by 1"
   },
   {
    "name": "filter_account_owner_name",
    "label": "Account Owner",
    "query": "select distinct(account_owner_name)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_l1_territory in (${filter_account_owner_l1_territory:singlequote})\n  and account_owner_l3_territory in (${filter_account_owner_l3_territory:singlequote})\n  and account_owner_l4_territory in (${filter_account_owner_l4_territory:singlequote})\n  and account_owner_l6_territory in (${filter_account_owner_l6_territory:singlequote})\n  and account_owner_segment      in (${filter_account_owner_segment:singlequote})\n  and account_owner_seller_type  in (${filter_account_owner_seller_type:singlequote})\n\norder by 1"
   },
   {
    "name": "filter_account_owner_id",
    "label": "Account Owner ID",
    "query": "select distinct(account_owner_id)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_l1_territory in (${filter_account_owner_l1_territory:singlequote})\n  and account_owner_l3_territory in (${filter_account_owner_l3_territory:singlequote})\n  and account_owner_l4_territory in (${filter_account_owner_l4_territory:singlequote})\n  and account_owner_l6_territory in (${filter_account_owner_l6_territory:singlequote})\n  and account_owner_segment      in (${filter_account_owner_segment:singlequote})\n  and account_owner_seller_type  in (${filter_account_owner_seller_type:singlequote})\n  and account_owner_name         in (${filter_account_owner_name:singlequote})\n\norder by 1\n"
   },
   {
    "name": "parameter_sdr_name",
    "label": "SDR",
    "query": "select distinct(account_mapped_sdr_name)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})"
   },
   {
    "name": "parameter_sdr_id",
    "label": "SDR ID",
    "query": "select distinct(account_mapped_sdr_id)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})\n  and account_mapped_sdr_name in (${parameter_sdr_name:singlequote})"
   },
   {
    "name": "parameter_se_name",
    "label": "SE",
    "query": "select distinct(account_solutions_engineer_name)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})"
   },
   {
    "name": "parameter_se_id",
    "label": "SE ID",
    "query": "select distinct(account_solutions_engineer_id)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})\n  and account_solutions_engineer_name in (${parameter_se_name:singlequote})"
   },
   {
    "name": "parameter_oa_manager_name",
    "label": "OA Manager",
    "query": "select distinct(account_observability_architect_manager_name)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})"
   },
   {
    "name": "parameter_oa_manager_id",
    "label": "OA Manager ID",
    "query": "select distinct(account_observability_architect_manager_id)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})\n  and account_observability_architect_manager_name in (${parameter_oa_manager_name:singlequote})"
   },
   {
    "name": "parameter_oa_name",
    "label": "OA",
    "query": "select distinct(account_observability_architect_name)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})\n  and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})"
   },
   {
    "name": "parameter_oa_id",
    "label": "OA ID",
    "query": "select distinct(account_observability_architect_id)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})\n  and account_observability_architect_name in (${parameter_oa_name:singlequote})\n  and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})"
   },
   {
    "name": "parameter_is_account_assigned_to_ae",
    "label": "Assigned to AE",
    "query": "select distinct(is_account_assigned_to_ae_filter)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})\n  and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})"
   },
   {
    "name": "parameter_is_territory_parent",
    "label": "Is Territory Parent Account",
    "query": "select distinct(is_territory_parent_filter)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n"
   },
   {
    "name": "filter_billing_country",
    "label": "Billing Country",
    "query": "select distinct(account_billing_country)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})"
   },
   {
    "name": "filter_billing_state_province",
    "label": "Billing State / Province",
    "query": "select distinct(account_billing_state_province)\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details\n\nwhere account_owner_id in (${filter_account_owner_id:singlequote})\n  and account_billing_country in (${filter_billing_country:singlequote})"
   },
   {
    "name": "filter_attainment_band_last_month",
    "label": "Attainment Band (vs Committed MRR), Last Month",
    "query": "with base_cte as (\n  select\n    consumption_committed_mrr_attainment_band_name_last_month as label\n    , consumption_committed_mrr_attainment_band_number_last_month as sort\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  GROUP BY 1, 2\n)\n\nselect label\n\nfrom base_cte\n\norder by sort"
   },
   {
    "name": "filter_projected_attainment_band_current_month",
    "label": "Projected Attainment Band (vs Committed MRR), Current Month",
    "query": "with base_cte as (\n  select\n    consumption_committed_mrr_attainment_band_name_projected_current_month as label\n    , consumption_committed_mrr_attainment_band_number_projected_current_month as sort\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  GROUP BY 1, 2\n)\n\nselect label\n\nfrom base_cte\n\norder by sort"
   }
  ]
 },
 "panels": [
  {
   "type": "marcusolsson-dynamictext-panel",
   "gridPos": { "h": 3, "w": 17, "x": 0, "y": 0 },
   "options": {
    "content": "<div style=\"float: left; margin-right: 20px;\">\n  <img src=\"http://samuelgaren.com/grafana/dashboard_assets/logo_territory_navigator.png\" style=\"height: 80px; padding-top: 10px;\"/>\n</div>\n\n<div style=\"float: left;\">\n  <p style=\"font-size: 32px; margin: 0;\">Territory Navigator</p>\n  <p style=\"font-size: 24px;\">v1.4</p>\n</div>"
   },
   "targets": [
    { "rawSql": "select 0 as test" }
   ]
  },
  { "title": "Summary (# of Accounts)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect count(a.account_id) as ct\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sum(net_nacv_split) as val\n\nfrom territory_nav.revops_reporting_opp_split as o\n\ninner join account_filter_cte on account_filter_cte.account_id = o.account_id\n\nwhere stage_number between 3 and 6\n  and net_nacv_ttl > 0"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sum(net_nacv_split) as val\n\nfrom territory_nav.revops_reporting_opp_split as o\n\ninner join account_filter_cte on account_filter_cte.account_id = o.account_id\n\nwhere stage_number = 7\n  and close_date between '${__from:date}'::date and '${__to:date}'::date\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect count(distinct(a.account_id)) as ct\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte as f on f.account_id = a.account_id\n\nwhere has_ae_sdr_meeting\n  or has_other_ae_sdr_engagement"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sum(ct_opt_ins_marketing_ops) as ct\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect count(CASE WHEN a.account_funnel_score_number = 1 THEN a.account_id ELSE null END) as ct_contracted\n  , count(CASE WHEN a.account_funnel_score_number != 1 THEN a.account_id ELSE null END) as ct_prospect\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 5, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect count(distinct(CASE WHEN stage_number between 3 and 6 and net_nacv_ttl > 0 THEN o.account_id ELSE null END)) as ct_accts_qp\n  , (count(distinct(CASE WHEN stage_number between 3 and 6 and net_nacv_ttl > 0 THEN o.account_id ELSE null END)))::numeric / NULLIF(count(distinct(o.account_id)), 0) as share_accts_qp\n\nfrom territory_nav.revops_reporting_opp_split as o\n\ninner join account_filter_cte on account_filter_cte.account_id = o.account_id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect opp_type_qbr\n  , count(distinct(o.account_id)) as ct_accts\n\nfrom territory_nav.revops_reporting_opp_split as o\n\ninner join account_filter_cte on account_filter_cte.account_id = o.account_id\n\nwhere stage_number = 7\n  and net_nacv_ttl > 0\n  and close_date between '${__from:date}'::date and '${__to:date}'::date\n\nGROUP BY 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect count(distinct(CASE WHEN has_ae_sdr_meeting THEN a.account_id ELSE null END)) as ct_ae_sdr_meeting\n  , count(distinct(CASE WHEN has_other_ae_sdr_engagement AND NOT has_ae_sdr_meeting THEN a.account_id ELSE null END)) as ct_other_ae_sdr_engagement\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte as f on f.account_id = a.account_id"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect (sum(coalesce(ct_opt_ins_contacted_l6m_marketing_ops, 0)))::numeric / NULLIF(sum(coalesce(ct_opt_ins_marketing_ops, 0)), 0) as share\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Accounts by TAM (Family)",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect coalesce(tam_category_family, '0. None') as label\n  , count(a.account_id) as ct\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\nGROUP BY 1\n\norder by 1 desc\n"
    }
   ]
  },
  {
   "title": "Accounts by Account Funnel Rank",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect replace(account_funnel_score_name, 'Campain', 'Campaign') as label\n  , count(a.account_id) as ct\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\nGROUP BY 1\n\norder by 1\n"
    }
   ]
  },
  {
   "title": "Accounts by Behavior Signal",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect company_behavior_signal_marketing_ops as label\n  , count(a.account_id) as ct\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\nGROUP BY 1\n\norder by 1\n"
    }
   ]
  },
  {
   "title": "Accounts by Sales Activity Pulse",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sales_activity_pulse_marketing_ops as label\n  , count(a.account_id) as ct\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\nGROUP BY 1\n\norder by 1\n"
    }
   ]
  },
  { "title": "Current Customers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\n\n\nselect sum(arr_curr) as val\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 5, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sum(consumption_weighted_last_month) as consumption\n  , sum(consumption_weighted_quota_last_month) as month_target\n  , sum(committed_mrr_last_month) as committed_mrr\n\n  , (sum(consumption_weighted_last_month_with_quota))::numeric / NULLIF(sum(committed_mrr_last_month), 0) as attain_month_target\n  , (sum(consumption_weighted_last_month_with_committed_mrr))::numeric / NULLIF(sum(committed_mrr_last_month), 0) as attain_committed_mrr\n\n  , TO_CHAR(current_date - interval '1 month', 'Month') || ' Consumption' as consumption_label\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\n--where account_funnel_score_number = 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sum(consumption_weighted_last_month) as consumption\n  , sum(consumption_weighted_quota_last_month) as month_target\n  , sum(committed_mrr_last_month) as committed_mrr\n\n  , (sum(consumption_weighted_last_month_with_quota))::numeric / NULLIF(sum(consumption_weighted_quota_last_month), 0) as attain_month_target\n  , (sum(consumption_weighted_last_month_with_committed_mrr))::numeric / NULLIF(sum(committed_mrr_last_month), 0) as attain_committed_mrr\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\n--where account_funnel_score_number = 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sum(consumption_weighted_projected_current_month) as consumption\n  , sum(consumption_weighted_quota_current_month) as month_target\n  , sum(committed_mrr_current_month) as committed_mrr\n\n  , (sum(consumption_weighted_projected_current_month_with_quota))::numeric / NULLIF(sum(committed_mrr_current_month), 0) as attain_month_target\n  , (sum(consumption_weighted_projected_current_month_with_committed_mrr))::numeric / NULLIF(sum(committed_mrr_current_month), 0) as attain_committed_mrr\n\n  , TO_CHAR(current_date, 'Month') || ' Proj. Consumption' as consumption_label\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\n--where account_funnel_score_number = 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sum(consumption_weighted_projected_current_month) as consumption\n  , sum(consumption_weighted_quota_current_month) as month_target\n  , sum(committed_mrr_current_month) as committed_mrr\n\n  , (sum(consumption_weighted_projected_current_month_with_quota))::numeric / NULLIF(sum(consumption_weighted_quota_current_month), 0) as attain_month_target\n  , (sum(consumption_weighted_projected_current_month_with_committed_mrr))::numeric / NULLIF(sum(committed_mrr_current_month), 0) as attain_committed_mrr\n\n  , TO_CHAR(current_date, 'Month') || ' Proj. Consumption' as consumption_label\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\n--where account_funnel_score_number = 1"
    }
   ]
  },
  {
   "title": "Product Usage Waterfall",
   "type": "volkovlabs-table-panel",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\n, accounts_cte as (\n  select a.account_id\n    , uses_visualization_status\n    , uses_metrics_status\n    , uses_logs_status\n    , uses_traces_status\n    , uses_profiles_status\n    , uses_k6_status\n    , uses_synthetics_status\n    , uses_frontend_observability_status\n    , uses_application_observability_status\n    , uses_kubernetes_monitoring_status\n    , uses_irm_status\n    , uses_database_observability_status\n    , uses_grafana_assistant_status\n\n  from territory_nav.revops_reporting_territory_navigator_account_details as a\n\n  inner join account_filter_cte as f on f.account_id = a.account_id\n\n  where account_funnel_score_number = 1 --contracted only\n)\n\n, visualization_usage_cte as (\n  select 'Visualization' as label\n    , 1 as sort\n    , uses_visualization_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, metrics_usage_cte as (\n  select 'Metrics' as label\n    , 2 as sort\n    , uses_metrics_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, logs_usage_cte as (\n  select 'Logs' as label\n    , 3 as sort\n    , uses_logs_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, traces_usage_cte as (\n  select 'Traces' as label\n    , 4 as sort\n    , uses_traces_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, profiles_usage_cte as (\n  select 'Profiles' as label\n    , 5 as sort\n    , uses_profiles_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, k6_usage_cte as (\n  select 'K6' as label\n    , 6 as sort\n    , uses_k6_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, synthetics_usage_cte as (\n  select 'Synthetics' as label\n    , 7 as sort\n    , uses_synthetics_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, frontend_observability_usage_cte as (\n  select 'FE O11y' as label\n    , 8 as sort\n    , uses_frontend_observability_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, application_observability_usage_cte as (\n  select 'App O11y' as label\n    , 9 as sort\n    , uses_application_observability_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, kubernetes_monitoring_usage_cte as (\n  select 'K8s Monitoring' as label\n    , 10 as sort\n    , uses_kubernetes_monitoring_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, irm_usage_cte as (\n  select 'IRM' as label\n    , 11 as sort\n    , uses_irm_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, database_observability_usage_cte as (\n  select 'DB O11y' as label\n    , 12 as sort\n    , uses_database_observability_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, grafana_assistant_usage_cte as (\n  select 'Grafana Assistant' as label\n    , 13 as sort\n    , uses_grafana_assistant_status as status\n    , count(distinct(account_id)) as ct\n\n  from accounts_cte\n\n  GROUP BY 1, 2, 3\n)\n\n, union_cte as (\n  select * from visualization_usage_cte\n\n  union all\n\n  select * from metrics_usage_cte\n\n  union all\n\n  select * from logs_usage_cte\n\n  union all\n\n  select * from traces_usage_cte\n\n  union all\n\n  select * from profiles_usage_cte\n\n  union all\n\n  select * from k6_usage_cte\n\n  union all\n\n  select * from synthetics_usage_cte\n\n  union all\n\n  select * from frontend_observability_usage_cte\n\n  union all\n\n  select * from application_observability_usage_cte\n\n  union all\n\n  select * from kubernetes_monitoring_usage_cte\n\n  union all\n\n  select * from irm_usage_cte\n\n  union all\n\n  select * from database_observability_usage_cte\n\n  union all\n\n  select * from grafana_assistant_usage_cte\n)\n\n, map_labels_cte as (\n  select label\n    , sort\n\n  from union_cte\n\n  GROUP BY 1, 2\n)\n\n, map_statuses_cte as (\n  select distinct(uses_visualization_status) as status\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  GROUP BY 1\n)\n\n\n\nselect\n  map_labels_cte.label\n  , CASE WHEN map_statuses_cte.status = '' THEN 'Not Using' ELSE map_statuses_cte.status END as status\n  , coalesce(union_cte.ct, 0) as ct\n\nfrom map_labels_cte\nCROSS JOIN map_statuses_cte\n\nleft join union_cte on union_cte.label = map_labels_cte.label\n  and union_cte.status = map_statuses_cte.status\n\norder by map_labels_cte.sort, map_labels_cte.label, map_statuses_cte.status\n\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sum(consumption_weighted_last_month) as consumption\n  , sum(consumption_weighted_quota_last_month) as month_target\n  , sum(committed_mrr_last_month) as committed_mrr\n\n  , (sum(consumption_weighted_last_month_with_quota))::numeric / NULLIF(sum(committed_mrr_last_month), 0) as attain_month_target\n  , (sum(consumption_weighted_last_month_with_committed_mrr))::numeric / NULLIF(sum(committed_mrr_last_month), 0) as attain_committed_mrr\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\n--where account_funnel_score_number = 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sum(consumption_weighted_projected_current_month) as consumption\n  , sum(consumption_weighted_quota_current_month) as month_target\n  , sum(committed_mrr_current_month) as committed_mrr\n\n  , (sum(consumption_weighted_projected_current_month_with_quota))::numeric / NULLIF(sum(committed_mrr_current_month), 0) as attain_month_target\n  , (sum(consumption_weighted_projected_current_month_with_committed_mrr))::numeric / NULLIF(sum(committed_mrr_current_month), 0) as attain_committed_mrr\n\n  , TO_CHAR(current_date, 'Month') || ' Proj. Consumption' as consumption_label\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\n--where account_funnel_score_number = 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\n\n\nselect sum(arr_cloud_curr) as val_cloud\n  , sum(arr_enterprise_curr) as val_enterprise\n\nfrom territory_nav.revops_reporting_territory_navigator_account_details as a\n\ninner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\n"
    }
   ]
  },
  {
   "title": "Attain of Committed MRR, Last Month",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 5, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\n, base_cte as (\n  select coalesce(consumption_committed_mrr_attainment_band_name_last_month, 'No Consumption_Quota') as label\n    , coalesce(consumption_committed_mrr_attainment_band_number_last_month, -1) as sort\n    , a.account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details as a\n\n  inner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\n  where account_funnel_score_number = 1\n)\n\nselect label\n  , count(distinct(account_id)) as ct\n\nfrom base_cte\n\ngroup by sort, label\n\norder by sort, label"
    }
   ]
  },
  {
   "title": "Proj Attain of Committed MRR, This Month",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 5, "x": 11, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\n, base_cte as (\n  select coalesce(consumption_committed_mrr_attainment_band_name_projected_current_month, 'No Consumption_Quota') as label\n    , coalesce(consumption_committed_mrr_attainment_band_number_projected_current_month, -1) as sort\n    , a.account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details as a\n\n  inner join account_filter_cte on account_filter_cte.account_id = a.account_id\n\n  where account_funnel_score_number = 1\n)\n\nselect label\n  , count(distinct(account_id)) as ct\n\nfrom base_cte\n\ngroup by sort, label\n\norder by sort, label"
    }
   ]
  },
  {
   "type": "canvas",
   "gridPos": { "h": 1, "w": 4, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\nselect sum(net_racv_split) as val\n  , count(distinct(o.account_id)) as ct_accts \n\nfrom territory_nav.revops_reporting_opp_split as o\n\ninner join account_filter_cte on account_filter_cte.account_id = o.account_id\n\nwhere stage_number < 7\n  and close_date between '${__from:date}'::date and '${__to:date}'::date\n  and net_racv_ttl > 0\n\n"
    }
   ]
  },
  { "title": "Opportunity Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Open Opportunities",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "rawSql": "with account_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n)\n\n, opportunities_cte as (\n  select\n    o.account_id\n    , t.account_name\n    , t.account_id_territory_parent\n    , t.account_name_territory_parent\n    , opp_id\n    , opp_name\n    , opp_type_qbr\n    , stage_name\n    , fq_close_date\n    , close_date\n    , sum(net_nacv_split) as net_nacv\n    , sum(net_racv_split) as net_racv\n    , sum(net_tcv_split) as net_tcv\n    , sum(services_split) as services\n    , CASE WHEN is_cro_forecast THEN '✔︎' ELSE '' END as is_cro_forecast\n    , CASE WHEN is_vp_forecast THEN '✔︎' ELSE '' END as is_vp_forecast\n    , CASE WHEN is_rvp_forecast THEN '✔︎' ELSE '' END as is_rvp_forecast\n    , CASE WHEN is_rsd_forecast THEN '✔︎' ELSE '' END as is_rsd_forecast\n    , CASE WHEN is_ae_forecast THEN '✔︎' ELSE '' END as is_ae_forecast\n\n    , case when stage_number between 3 and 6 then 2\n      when stage_number = 2 then 1\n      else 0\n      end as stage_category\n\n  from territory_nav.revops_reporting_opp_split as o\n\n  inner join account_filter_cte as f on f.account_id = o.account_id\n\n  left join territory_nav.revops_reporting_territory_navigator_account_details as t on t.account_id = o.account_id\n\n  where close_date between '${__from:date}'::date and '${__to:date}'::date\n    and stage_number <= 6\n\n  GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 16, 17, 18, 19, 20\n)\n\nselect *\n\nfrom opportunities_cte\n\norder by net_nacv desc, net_racv desc, net_tcv desc, services desc, opp_name, opp_id"
    }
   ]
  },
  { "title": "Appendix", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Org Details",
   "type": "table",
   "description": "[Column Definitions & Sales Plays](https://docs.google.com/document/d/1wZg8a59SWanCmz1Y_JxpcX3r3Jm_grpe0hLzYS2vyCk/edit?tab=t.0#heading=h.km9ccgdbshp8)",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 59 },
   "targets": [
    {
     "rawSql": "with\naccount_filter_cte as (\n  select account_id\n\n  from territory_nav.revops_reporting_territory_navigator_account_details\n\n  where account_owner_id in (${filter_account_owner_id:singlequote})\n    and account_mapped_sdr_id in (${parameter_sdr_id:singlequote})\n    and account_solutions_engineer_id in (${parameter_se_id:singlequote})\n    and account_observability_architect_id in (${parameter_oa_id:singlequote})\n    and account_observability_architect_manager_id in (${parameter_oa_manager_id:singlequote})\n    and is_account_assigned_to_ae_filter in (${parameter_is_account_assigned_to_ae:singlequote})\n    and is_territory_parent_filter in (${parameter_is_territory_parent:singlequote})\n    and account_billing_country in (${filter_billing_country:singlequote})\n    and account_billing_state_province in (${filter_billing_state_province:singlequote})\n    and consumption_committed_mrr_attainment_band_name_last_month in (${filter_attainment_band_last_month:singlequote})\n    and consumption_committed_mrr_attainment_band_name_projected_current_month in (${filter_projected_attainment_band_current_month:singlequote})\n),\n\n-- Use the materialized dbt model instead of rebuilding all the logic\nterritory_navigator_base as (\n    select *\n    from territory_nav.rpt_self_serve_territory_navigator_orgs\n)\n\nSELECT\n  tnb.sfdc_account_id,\n  tnb.sfdc_account_name,\n  tnb.org_slug,\n  tnb.org_type,\n  tnb.revops_account_funnel,\n  tnb.sales_plays,\n  tnb.warmth_rank_warmth_model,\n  tnb.last_activity_date,\n  tnb.arr,\n  tnb.mrr_delta,\n  tnb.billable_users,\n  tnb.billable_users_delta,\n  tnb.billable_series,\n  tnb.billable_series_delta,\n  tnb.billable_logs,\n  tnb.billable_logs_delta,\n  tnb.billable_traces,\n  tnb.billable_traces_delta,\n  tnb.billable_profiles,\n  tnb.billable_profiles_delta,\n  tnb.billable_k6_vuh,\n  tnb.billable_k6_vuh_delta,\n  tnb.billable_irm_users,\n  tnb.billable_irm_user_delta,\n  tnb.billable_app_o11y_host_hours,\n  tnb.billable_app_o11y_host_hours_delta,\n  tnb.billable_fe_o11y_sessions,\n  tnb.billable_fe_o11y_sessions_delta,\n  tnb.billable_sm_checks,\n  tnb.billable_sm_checks_delta,\n  tnb.hg_datasource_cnts,\n  tnb.integrations,\n  tnb.arr_sparkline_values,\n  tnb.hm_sparkline_values,\n  tnb.k8s_o11y_pricing_type\n\nFROM territory_navigator_base tnb\nINNER JOIN account_filter_cte \n  ON account_filter_cte.account_id = tnb.sfdc_account_id"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 77 },
   "options": {
    "content": "<p>\n  Org Details courtesy of Self-Serve Analytics. Contact <a href=\"https://raintank-corp.slack.com/archives/C07NBDSCGJX\">#self-serve-analytics</a> for more information.\n</p>\n<p>\n  NOTE: The above panel may crash if too many accounts are selected in the filters at the top of the dashboard. If the panel crashes, try selecting fewer accounts (10k or fewer seems to work well).\n<p>\n\n"
   }
  }
 ]
}