services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    container_name: 'grafana-itself'
    build:
      args:
        grafana_version: ${GRAFANA_VERSION:-12.3.3}
        grafana_image: ${GRAFANA_IMAGE:-grafana}
    environment:
      GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH: /etc/grafana/provisioning/dashboards/cubeds-ecom-full-data-model.json
      GF_FEATURE_TOGGLES_ENABLE: 'tableNextGen,queryLibrary,sqlExpressions,dashboardDsAdHocFiltering,adhocFiltersInTooltips'
    depends_on:
      - cube

  cube:
    image: cubejs/cube:latest@sha256:f70716f70455decb4ec03a579d3c495c930c546ac3aababd0a854bb016f5680e
    ports:
      - 4000:4000
      - 15432:15432
    volumes:
      - ./dev-environment/cube:/cube/conf
    depends_on:
      - postgres

  postgres:
    image: postgres:18@sha256:059fa0289cc5a184034e05a1f4f6d6fd79f69dc718b8b04ab60b6b469eed411e
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jaffle_shop
    ports:
      - '5432:5432'
    volumes:
      - ./dev-environment/data/seeds/:/data/seeds/
      - ./dev-environment/data/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql
    # Enable SQL queries in the logs (minimal output)
    command:
      [
        'postgres',
        '-c',
        'log_statement=all',
        '-c',
        'log_line_prefix=',
        '-c',
        'log_duration=off',
        '-c',
        'log_parameter_max_length=0',
      ]
