views:
  - name: customer_directory

    cubes:
      - join_path: customers
        includes:
          - first_name
          - last_name
          - email
          - is_active
          - created_at
          - customer_segment
          - count
          - active_count
        prefix: false
