# Payments view - exposes payment data with related orders and customers
# This view provides a payment-centric perspective on the data, allowing you to
# analyze payments alongside order and customer information.

views:
  - name: payments

    cubes:
      - join_path: raw_payments
        includes:
          - id
          - order_id
          - payment_method
          - amount
          - tax
          - discount
          - processing_fee
          - refund_amount
          - created_at
          - is_successful
          - currency
          - total_amount
          - total_tax
          - total_discount
          - total_fees
          - avg_amount
          - avg_tax
          - min_amount
          - max_amount
          - count
          - unique_payment_methods
          - net_amount
          - effective_tax_rate
          - zero_amount_count
          - total_refunds
          - net_revenue
          - count_with_discount
          - avg_non_null_discount
          - successful_payment_count
          - failure_rate
          - total_amount_in_microdollars
          - amount_fraction_of_billion
          - near_max_int_test
          - scientific_notation_test
          - tiny_decimal_test
        prefix: true

      - join_path: raw_payments.raw_orders
        includes:
          - status
          - order_date
          - created_at
          - is_gift
          - priority
          - count
          - gift_count
          - avg_priority
        prefix: true

      - join_path: raw_payments.raw_orders.raw_customers
        includes:
          - first_name
          - last_name
          - email
          - is_active
          - created_at
          - customer_segment
          - count
          - active_count
        prefix: true
